blueprint:
  name: Ouverture automatique portail via Bluetooth voiture
  description: |
    Ouvre automatiquement un portail ou une porte de garage quand un appareil 
    se connecte au Bluetooth d'une voiture ET que cet appareil est physiquement 
    dans la zone définie (généralement la maison).
    
    ✅ Vérifie que l'appareil qui se connecte est bien dans la bonne zone
    ✅ Empêche l'ouverture si quelqu'un se connecte ailleurs
    ✅ Parfait pour automatiser l'arrivée sans intervention manuelle
    
  domain: automation
  source_url: https://github.com/Ostenhard/ha/blob/main/blueprints/portail-bluetooth.yaml
  
  input:
    bluetooth_sensor:
      name: Capteur de connexion Bluetooth
      description: |
        Capteur qui détecte les connexions Bluetooth de l'appareil.
        Format: sensor.xxx_bluetooth_connection
        
        Pour activer ce capteur:
        1. App Home Assistant Companion > Paramètres
        2. Gérer les capteurs
        3. Activer "Bluetooth Connection"
      selector:
        entity:
          filter:
            - domain: sensor
          
    device_tracker:
      name: Traceur de l'appareil (même appareil)
      description: |
        Device tracker correspondant AU MÊME appareil que le capteur Bluetooth.
        
        ⚠️ IMPORTANT: Ce doit être le même appareil !
        Exemple: si bluetooth_sensor = sensor.sm_a525f_bluetooth_connection
        alors device_tracker = device_tracker.sm_a525f
      selector:
        entity:
          filter:
            - domain: device_tracker
          
    bluetooth_mac_addresses:
      name: Adresses MAC Bluetooth de la voiture
      description: |
        Liste des adresses MAC Bluetooth de votre voiture.
        Format: ["AA:BB:CC:DD:EE:FF", "11:22:33:44:55:66"]
        
        🔍 Comment trouver ces adresses:
        1. Connectez votre téléphone au Bluetooth de la voiture
        2. Home Assistant > Outils développeur > États
        3. Cherchez sensor.xxx_bluetooth_connection
        4. Regardez l'attribut "connected_paired_devices"
        5. Copiez les adresses exactement comme affichées
        
        💡 Astuce: Vous pouvez mettre plusieurs adresses si votre 
        voiture a plusieurs interfaces Bluetooth (radio, téléphone, etc.)
      default: []
      selector:
        object:
          
    target_zone:
      name: Zone de déclenchement
      description: |
        Zone dans laquelle l'appareil DOIT se trouver pour déclencher l'ouverture.
        
        Généralement: zone.home (Maison)
        Mais peut être: zone.travail, zone.lycee, etc.
      default: zone.home
      selector:
        entity:
          filter:
            - domain: zone
          
    cover_entity:
      name: Portail ou porte de garage à ouvrir
      description: |
        Entité du portail, porte de garage ou barrière à ouvrir.
      selector:
        entity:
          filter:
            - domain: cover
          
mode: single
max_exceeded: silent

variables:
  bluetooth_addresses: !input bluetooth_mac_addresses

trigger:
  - platform: numeric_state
    entity_id: !input bluetooth_sensor
    above: 0

condition:
  # Condition 1: Le portail doit être fermé
  - condition: state
    entity_id: !input cover_entity
    state: closed
    
  # Condition 2: L'appareil qui se connecte DOIT être dans la zone définie
  - condition: zone
    entity_id: !input device_tracker
    zone: !input target_zone
    
  # Condition 3: Le nombre de connexions Bluetooth a augmenté (= connexion, pas déconnexion)
  - condition: template
    value_template: >
      {% set raw_values = trigger.to_state.attributes.connected_paired_devices %}
      
      {# Vérifier que raw_values existe et n'est pas None #}
      {% if raw_values is not none and raw_values | length > 0 %}
        {# Extraire uniquement les adresses MAC de chaque élément #}
        {# Le regex cherche 17 caractères composés de chiffres, lettres A-F et deux-points #}
        
        {% set connectes = raw_values | map('regex_findall', '([0-9A-F:]{17})', ignorecase=True) | map('first') | list %}
                      
        {# Comparer les deux listes propres #}
        {{ connectes | intersect(bluetooth_addresses) | count > 0 }}
      {% else %}
        {# Si pas de données, la condition échoue #}
        false
      {% endif %}

action:
  - service: cover.open_cover
    target:
      entity_id: !input cover_entity
    data: {}